name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:    # uses GitHub's checkout action to checkout code form the master branch
    - name: checkout
      uses: actions/checkout@v2      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
    - name: Publish .NET Core Project
      run: dotnet publish wrath-wiki.csproj -c Release -o release --nologo
    - name: Change base-tag in index.html from / to wrath-wiki
      run: sed -i 's/<base href="\/" \/>/<base href="\/wrath-wiki\/" \/>/g' release/wwwroot/index.html
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: 'release/wwwroot'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
